### ISSUE TITLE
frag is not comiled

### ISSUE THREAD

**Issue by mnisb3537** [TheCherno/Flappy#1]
glCompileShader(fragID); 
console : Failed to compile fragment shader!
 how to solve this issue?

**Comment by jondmarien** [comment]
I have it too, I figured it out, my graphics card cannot process the size of the shader/image or something. I just printed the glError thing and googled it.

**Comment by TheCherno** [comment]
What else does the console say? You should be printing out the shader compilation error log, so it should tell you what the problem is.

**Comment by mnisb3537** [comment]
console says:
Failed to compile fragment shader!
ERROR: 0:18: 'assign' :  l-value required "_I;DATA;tc" (can't modify a varying)

**Comment by TheCherno** [comment]
Try the following code for your `pipe.frag` shader:

``` GLSL
#version 330 core

layout (location = 0) out vec4 color;

in DATA
{
    vec2 tc;
    vec3 position;
} fs_in;

uniform vec2 bird;
uniform sampler2D tex;
uniform int top;

void main()
{
    vec2 tc = fs_in.tc;
    if (top == 1)
        tc.y = 1.0 - tc.y;

    color = texture(tex, tc);
    if (color.w < 1.0)
        discard;
    color *= 2.0 / (length(bird - fs_in.position.xy) + 1.5) + 0.5;
    color.w = 1.0;
}
```

**Comment by mnisb3537** [comment]
ya. It worked for me. But now screen scrolls rightwards without showing bird and if I press any key it freezes.

**Comment by TheCherno** [comment]
Please open another issue for that.
